services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NPM_CONFIG_REGISTRY=${NPM_CONFIG_REGISTRY}
        - GITHUB_MIRROR_PREFIX=${GITHUB_MIRROR_PREFIX}
        - NODE_MAX_OLD_SPACE_SIZE=${NODE_MAX_OLD_SPACE_SIZE}
        - HF_ENDPOINT=${HF_ENDPOINT}
        - PIP_INDEX_URL=${PIP_INDEX_URL}
        - UV_INDEX_URL=${UV_INDEX_URL}
        - PIP_TRUSTED_HOST=${PIP_TRUSTED_HOST}
        - PYTORCH_INDEX_URL_CPU=${PYTORCH_INDEX_URL_CPU}
        - PYTORCH_INDEX_URL_CUDA=${PYTORCH_INDEX_URL_CUDA}
        - APT_MIRROR=${APT_MIRROR}
        - APT_SECURITY_MIRROR=${APT_SECURITY_MIRROR}
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      ollama:
        condition: service_started
    ports:
      - ${OPEN_WEBUI_PORT-8080}:8080
    environment:
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL-http://ollama:11434}
      OPENAI_API_BASE_URL: ${OPENAI_API_BASE_URL-http://host.docker.internal:8081/v1}
      OPENAI_API_KEY: ${OPENAI_API_KEY-}
      OPENAI_API_BASE_URLS: ${OPENAI_API_BASE_URLS-http://host.docker.internal:8081/v1}
      OPENAI_API_KEYS: ${OPENAI_API_KEYS-}
      ENABLE_OPENAI_API: ${ENABLE_OPENAI_API-true}
      ENABLE_OLLAMA_API: ${ENABLE_OLLAMA_API-false}
      HF_ENDPOINT: ${HF_ENDPOINT-}
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY-}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
